// Mocks generated by Mockito 5.3.2 from annotations
// in weekly_task2/test/api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:weekly_task2/models/game_model.dart' as _i6;
import 'package:weekly_task2/models/gamebycategory_model.dart' as _i7;
import 'package:weekly_task2/models/gamedetail_model.dart' as _i3;
import 'package:weekly_task2/service/api.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGameDetailModel_1 extends _i1.SmartFake
    implements _i3.GameDetailModel {
  _FakeGameDetailModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ServiceAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceAPI extends _i1.Mock implements _i4.ServiceAPI {
  MockServiceAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  _i5.Future<List<_i6.GameModel>> getAllGamesApi() => (super.noSuchMethod(
        Invocation.method(
          #getAllGamesApi,
          [],
        ),
        returnValue: _i5.Future<List<_i6.GameModel>>.value(<_i6.GameModel>[]),
      ) as _i5.Future<List<_i6.GameModel>>);
  @override
  _i5.Future<_i3.GameDetailModel> getDetailGamesApi(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailGamesApi,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.GameDetailModel>.value(_FakeGameDetailModel_1(
          this,
          Invocation.method(
            #getDetailGamesApi,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.GameDetailModel>);
  @override
  _i5.Future<List<_i7.GameByCategoryModel>> getGameByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGameByCategory,
          [category],
        ),
        returnValue: _i5.Future<List<_i7.GameByCategoryModel>>.value(
            <_i7.GameByCategoryModel>[]),
      ) as _i5.Future<List<_i7.GameByCategoryModel>>);
}
